### ISSUE TITLE
preprocess issues

### ISSUE THREAD

**Issue by JudyCodes321** [gerwang/facial-detail-manipulation#1]
When I run pre-precess code, I meet this error "ModuleNotFoundError: No module named 'sklearn.mixture.gaussian_mixture". It occurs at "self.exp_gmm = pickle.load(f)" .But I can't find where import "sklearn"?
![image](https://user-images.githubusercontent.com/46815856/193577900-0d4ba850-a177-4832-8ef2-d31eff33ecc7.png)

**Comment by gerwang** [comment]
The `sklearn` module is required when loading the FaceScape 3DMM. It is packed into a pickle file. Therefore `sklearn` is required even if it doesn't appear in any python code. Please install the exact version of `scikit-learn` listed in our `requirements.txt`.

**Comment by JudyCodes321** [comment]
Thanks~
