### ISSUE TITLE
Environment configuration problems

### ISSUE THREAD

**Issue by Lipolan** [gerwang/facial-detail-manipulation#2]
**Hello, I'm a novice, and I appreciate your work very much. But when I try to match the environment, I encounter these two problems, and I'm not very good at it. Can you tell me in detail what I should do? Thank you.**
1.  Install [ibug-face-detection](https://github.com/hhj1897/face_detection) and [ibug-face-alignment](https://github.com/hhj1897/face_alignment).
2. Install Blender 3.2 and FFmpeg. Make sure blender and ffmpeg can be accessed in shell, or you can set the blender_path and ffmpeg_path in ./experiments/both_cond_launcher.py.
3. Install scipy for Blender. Typically, we should first download the [get-pip](https://github.com/pypa/get-pip) script, run ${blender_path}/3.2/python/bin/python3.10 get-pip.py and then run ${blender_path}/3.2/python/bin/python3.10 -m pip install scipy.

**Comment by gerwang** [comment]
Thanks for your attention. We assume an environment setup on a **Linux** machine. 

For 1, go to the GitHub pages of the two projects and follow their instructions. For 2 and 3, you can download the Linux version of Blender (https://download.blender.org/release/Blender3.2/) and FFmpeg (https://ffmpeg.org/download.html#build-linux) or install it from your os package manager (`apt` for Ubuntu and `pacman` for Arch Linux).

**Comment by Lipolan** [comment]
> 
Download from https://facescape.nju.edu.cn/Page_Download/ 
Thank you for your reply. Another small problem is web page maintenance when downloading the model. Can you provide some information? Thank you very much!

**Comment by gerwang** [comment]
You need to sign a license and send it to facescape's authors to get a download link. Please see here https://github.com/zhuhao-nju/facescape

**Comment by Lipolan** [comment]
> 
ok! thank you very much!
