### ISSUE TITLE
LPIPS loss issue

### ISSUE THREAD

**Issue by JudyCodes321** [gerwang/facial-detail-manipulation#3]
I meet a problem lpips loss <0 in training.
Excuse me, have you ever meet this problem? @gerwang

**Comment by gerwang** [comment]
The LPIPS loss is outputted by a network, so it is possible to be negative, but I'm not sure.
You can post an issue on https://github.com/richzhang/PerceptualSimilarity to ask whether it is an issue.
I remember we turned off LPIPS loss in training (although there is code for it) and used feature matching loss which has a similar effect.
